language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
#  - "3.7-dev"  # Forgot we need libyaml to test ourselves

install:
  - "pip install -r requirements-ci.txt"

script:
  # ignore output from install
  - python setup.py install &> /dev/null
  - snekchek
  # In case snekchek fails silently, use git diff for changelog
  - PAGER='' git diff

cache: pip

notifications:
  email: false
